#!/bin/sh
#
# Copyright (C) 2017 DEVELICT Solutions s.r.o.
#

develict_set_banner() {
    [ -f /etc/openwrt_release ] && . /etc/openwrt_release

    cat > /etc/banner <<-EOF

 FW: $DISTRIB_DESCRIPTION
 --------------------------------------------
          DEVELICT Solutions s.r.o.

           http://www.develict.com
            support@develict.com
 --------------------------------------------

EOF
}

develict_set_banner

exit 0
